const CATEGORIES_LOADED = 'CATEGORIES_LOADED';
const GOODS_LOADED = 'GOODS_LOADED';
const NEW_REQUEST = 'NEW_REQUEST';
const ERROR = 'ERROR';
const PRODUCT_LOADED = 'PRODUCT_LOADED';
const ADDED_PRODUCT_TO_CART = 'ADDED_PRODUCT_TO_CART';
const PRODUCT_REMOVED = 'PRODUCT_REMOVED';
const PRODUCT_REMOVED_ALL = 'PRODUCT_REMOVED_ALL';
const BREAD_CRUMBS_CATEGORY_TITLE = 'BREAD_CRUMBS_CATEGORY_TITLE';
const CALСULATE_TOTAL_SUMM = 'CALСULATE_TOTAL_SUMM';
const CALСULATE_TOTAL_GOODS = 'CALСULATE_TOTAL_GOODS';
const BRANDS_LOADED = 'BRANDS_LOADED';
const BRAND_FILTER_LOADED = 'BRAND_FILTER_LOADED';
const CLEAR_BRAND_FILTER_LOADED = 'CLEAR_BRAND_FILTER_LOADED';
const BRAND_FILTER_DELETED = 'BRAND_FILTER_DELETED';
const RANGE_FILTER= 'RANGE_FILTER';
const SELECTED_CATEGORY = 'SELECTED_CATEGORY';
const INC_DEC_SORT= 'INC_DEC_SORT';
const REVIEWS_LOADED = 'REVIEWS_LOADED';
const RANGE_LOADED = 'RANGE_LOADED';
const CART_CLEARED = 'CART_CLEARED'

export {
    CATEGORIES_LOADED,
    GOODS_LOADED,
    NEW_REQUEST,
    ERROR,
    PRODUCT_LOADED,
    ADDED_PRODUCT_TO_CART,
    PRODUCT_REMOVED,
    PRODUCT_REMOVED_ALL,
    BREAD_CRUMBS_CATEGORY_TITLE,
    CALСULATE_TOTAL_SUMM,
    CALСULATE_TOTAL_GOODS,
    BRANDS_LOADED,
    BRAND_FILTER_LOADED,
    CLEAR_BRAND_FILTER_LOADED,
    BRAND_FILTER_DELETED,
    SELECTED_CATEGORY,
    INC_DEC_SORT,
    REVIEWS_LOADED,
    RANGE_FILTER,
    RANGE_LOADED,
    CART_CLEARED
    
}